project:
  type: book

book:
  title: "Defining Data Science"
  author: "Brian Wright and Peter Alonzi"
  date: "11/7/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - part: design.qmd
      chapters: 
        - design-sds.qmd
        - design-lab.qmd
        - design-external.qmd
        - design-case-study.qmd
    - part: value.qmd
      chapters: 
        - value-sds.qmd
        - value-lab.qmd
        - value-external.qmd
        - value-case-study.qmd
    - BSDS-Course-Info.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    
execute:
  freeze: auto