project:
  type: book

book:
  title: "Defining Data Science"
  author: "Brian Wright"
  date: "11/7/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - design.qmd
    - BSDS-Course-Info.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    
execute:
  freeze: auto



