project:
  type: book

book:
  title: "Defining Data Science"
  author: "Brian Wright and Peter Alonzi"
  date: "11/7/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - part: design.qmd
      chapters: 
        - design-sds.qmd
        - design-lab.qmd
        - design-external.qmd
        - design-case-study.qmd
    - part: value.qmd
      chapters: 
        - value-sds.qmd
        - value-lab.qmd
        - value-lab-II.qmd
        - value-lab-III.qmd
        - value-external.qmd
        - value-case-study.qmd
    - part: "Systems"
      chapters: 
        - systems-sds.qmd
        - systems-lab.qmd
        - systems-external.qmd
        - systems-case-study.qmd
    - part: "Analytics"
      chapters: 
        - analytics-sds.qmd
        - analytics-lab.qmd
        - analytics-external.qmd
        - analytics-case-study.qmd
    - part: "Appendix"
      chapters: 
        - appendix-sources.qmd
    - BSDS-Course-Info.qmd
    - references.qmd
  favicon: /images/domains.png
  twitter-card: true
  site-url: http://definingdatascience.com/ 

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    
execute:
  freeze: auto

margin-footer: | 
  The GitHub repo for this book is here: <https://github.com/UVADS/DS1001>

margin-header: |
  ![](/images/domains.png)