---
title: "Relation to AI"
format: html
bibliography: references.bib
---

The four areas of data science defined here are surprisingly analogous to the four approaches to artificial intelligence defined by Russel and Norvig in their classic textbook on the subject [@russell1995: 5]. Their four part model was generated by combining the axes $thinking \leftrightarrow acting$ with $human \leftrightarrow rational$ as follows:

| behavior | mode       | systems                      |
|----------|------------|------------------------------|
| thinking | humanly    | cognitive models, ontologies |
| thinking | rationally | logic, laws of thought       |
| acting   | humanly    | Turing test, situated action |
| acting   | rationally | agents, bots                 |


Now, it is easy to see how the following analogies make sense:

$$
abstract : concrete :: thinking : action
$$

and

$$
human : rational :: human : machine
$$

Or, put in terms of a set of identities:

| AI       | DS       |
|----------|----------|
| abstract | thinking |
| concrete | action   |
| human    | human    |
| rational | machine  |

So it makes sense to compare the above table with this one for data science:

| level    | focus   | area      | topic                                          |
|----------|---------|-----------|------------------------------------------------|
| abstract | human   | design    | ontologies, data models, visualizations        |
| abstract | machine | analytics | math, logic, algorithms                        |
| concrete | human   | value     | ethics, research questions, value propositions |
| concrete | machine | systems   | hardware, software, security                   |

By comparing last columns of each table we can see that the 4+1 model of data science and Russell and Norvig's model of artificial intelligence share the same general space. The difference is that the former defines kinds of *acquired knowledge*, whereas the latter concerns kinds of *built systems*.

**References**

::: {#refs}
:::
