# Labs Rubric - Guess Who

DS 1001 - Spring 2023 - Professors Wright and Alonzi Due: End of lab period (or later that day) Submission format: Word doc or PDF summarizing your findings

Individual Assignment

**General Descripition:** This lab is design for you to reflect on the process used for winning the game Guess Who. Students should work in teams to play the game and take notes on the processes that work best for quickly guessing the opponents card. This will likely include the creation of a tree based decision diagram, a example will be provided in class.

Preparatory Assignments - None

**Why am I doing this?** In order to allow you to reflect on how data is used to generated decision/predictive algorithms and what issues could arise as a result. Work to incorporate the materials you've been exposed to up to this point as you work through the lab.

**What am I going to do?** You are working through a interactive process with your group to find the optimal list of yes/no questions for any given card. Play the game as many times as necessary to construct a list of the top five questions using a tree based diagram.

**Answer these questions:**

1.  In this situation what is the dataset and what is the algorithm?
2.  How did your approach to identifying cards change throughout the lab period?
3.  Are there cards that are easier to identify, why?
4.  This is just a game, but given the materials you've been exposed to what concerns do you have about this process and algorithmic decision making?

Tips for success:

-   Don't worry about winning
-   Work as a team with your group
-   Try to document the process used right at the start of the lab, don't wait till after you have played to start taking notes

How will I know I have succeeded

+-------------------+-----------------------------------------------------------------------------------------+
| Specs Category    | Specs Details                                                                           |
+:=================:+:========================================================================================+
| Formatting        | -   Submit Via Canvas                                                                   |
|                   | -   Text answers to questions                                                           |
+-------------------+-----------------------------------------------------------------------------------------+
| Text              | -   Goal: The questions are designed to be answer during or right after the lab period. |
|                   | -   Use a few sentences to answer each question in Canvas                               |
+-------------------+-----------------------------------------------------------------------------------------+

Acknowledgements: Special thanks for Jess Taggart from UVA CTE for coaching us. This structure is pulled directory from Steifer & Palmer (2020).