# Labs Rubric - Explainable AI Interview

DS 1001 - Spring 2023 - Professors Wright and Alonzi Due: End of lab period (or later that day) Submission format: Word doc or PDF summarizing your findings

Individual Assignment

**General Descripition:** This lab is designed for you to verbalize the concept of Explainable AI to someone that is unfamiliar with the concepts and track their responses.

Preparatory Assignments - None

**Why am I doing this?** This will allow you to work on communicating the concepts thus understanding them better and judging whether trust is increased with the knowledge that explainable approach to AI models are present.

**What am I going to do?** Interview three people that have somewhat limit knowledge of Machine Learning and AI. Ask the first two questions then provide a brief overview of Explainable AI and then ask the remaining three questions. After all three interviews are complete provide a brief summary of what patterns you notice (a paragraph or two is fine)

**Answer these questions:**

1.  Do you believe that AI has a large influence over society currently?
2.  On a scale from 1 to 10, with 10 being total trust and 1 being no trust: Do you believe that AI models can be trusted and used in a way that promotes positive outcomes for individuals and society?
3.  Give a brief overview of the Data Ethic concepts with a emphasis on Explainable AI models.
4.  Given what you just heard does that in anyway change your answer to question 2, such that, if explainable AI models were more commonly used would you be more likely to believe that they can promote positive outcomes for individuals and society? (scale of 1 to 10 for you belief the AI models can promote positive outcomes)
5.  Are you interested in learning more about Explainable AI as a concept?

Tips for success:

-   Keep your over of data Ethics and Explainable AI at a high level and use the slides provided in class as needed.
-   Feel free to improvise and ask additional questions if you'd like or change the questions slightly.

How will I know I have succeeded:

+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+
| Specs Category | Specs Details                                                                                                                                       |
+:==============:+:====================================================================================================================================================+
| Formatting     | -   Submit Via Canvas                                                                                                                               |
|                | -   Summary of your three interviews in one document                                                                                                |
|                | -   A reflection on any patterns you noticed in the answers                                                                                         |
+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+
| Text           | -   Goal: The interview is designed to be fairly quick, 10 minutes or so for each. All together the assignment should take approximately one hour.  |
+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------+

Acknowledgements: Special thanks for Jess Taggart from UVA CTE for coaching us. This structure is pulled directory from Steifer & Palmer (2020).